### ISSUE TITLE
Using this library to format phone number

### ISSUE THREAD

**Issue by orestesgaolin** [cedvdb/phone_numbers_parser#1]
I wonder if it is possible to use this library to _reverse_ its purpose i.e. to format a set of numbers into a phone number for a. given country:

> 1234567890 -> (US) -> 123-456-7890

**Comment by cedvdb** [comment]
The code used for formatting in PhoneNumberKit is rather small, so I will take a look soonish. https://github.com/marmelroy/PhoneNumberKit/blob/master/PhoneNumberKit/Formatter.swift

If anyone is interested in making a PR that would be welcome as well.

**Comment by bsutton** [comment]
Allowing formatting into local and national no.s would also be useful:

e.g. 
```dart
var phone = PhoneParser.parseRaw('+61383208100');
phone.toLocal == '0383208100';
phone.toNational = '61383208100';
```

**Comment by cedvdb** [comment]
If someone wants to have a go at this, I've separated the metadatas in multiple maps. `PhoneMetadataFormats` is the one that is required for this. It is expected that a new `PhoneNumberFormatter` class would be created to not increase the size of the library if one only needs the parsing and not the formatting, as it is hard to know in advance what is tree shaken and what is not.

Some inspiration here :

https://github.com/google/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/AsYouTypeFormatter.java

**Comment by cedvdb** [comment]
I've made a naive implementation this evening.

It needs some tweaking and requirements. Currently outputs this:

```dart
      final parser = PhoneParser();
      final phoneNumber = parser.parseWithIsoCode('FR', '499887733');
      final formatter = PhoneNumberFormatter();
      formatter.formatNsn(phoneNumber);  // '4 99 88 77 33';
```

**Comment by cedvdb** [comment]
I'm making some naive progress on this on the branch `formatter`
