### ISSUE TITLE
example number is considered invalid

### ISSUE THREAD

**Issue by EyMaddis** [cedvdb/phone_numbers_parser#18]
Hi,
I noticed that a test number I have `+44 7000000002` works in [libphonenumber](https://libphonenumber.appspot.com/phonenumberparser?number=%2B44+7000000002), but not [with this library](https://cedvdb.github.io/phone_form_field/#/).

I am not sure why, because it seems that you use libphonenumbers metadata...

**Comment by cedvdb** [comment]
Thanks, I'll take a look during the weekend. There are some slight differences between the two libraries though. One of which is that pattern matching is used to determine the validity of a phone number. If I recall correctly (I could be wrong here) libphonenumber does not do that by default for validation. The phone number might be valid when doing .validateWithLength().

In any case I will have a look this weekend

**Comment by cedvdb** [comment]
It seems like I introduced a bug in the last update I did, this is due to the zeroes. Thanks, I'll fix that tonight.

**Comment by cedvdb** [comment]
fixed in 4.2.0
