### ISSUE TITLE
provide a general PhoneNumberType

### ISSUE THREAD

**Issue by codenoobforreal** [cedvdb/phone_numbers_parser#21]
there is no 'general' type in PhoneNumberType.So I can't use validate method with general type.The 'type = null' behavior is add all PhoneNumberType related pattern to patterns list for pattern matching.
For number that only hit general pattern will  return false by validate method.

![image](https://user-images.githubusercontent.com/18373253/147081718-64be2bd5-f514-44ae-a330-07dbc7df4d83.png)

![image](https://user-images.githubusercontent.com/18373253/147081869-0a3dbc13-f7d7-446f-905b-2a50db585b67.png)

![image](https://user-images.githubusercontent.com/18373253/147081911-17d65872-e8c0-4f32-81b5-80b9eb97574b.png)

**Comment by cedvdb** [comment]
So you would want to use the library with a phone number that is neither a fixedLine nor a mobile phone number ? Just so I understand the use case is it like a police, ambulance number etc ?

**Comment by codenoobforreal** [comment]
> So you would want to use the library with a phone number that is neither a fixedLine nor a mobile phone number ? Just so I understand the use case is it like a police, ambulance phone number ? What does `53552200` represent is my question.
> 
> That's important to know if the underlying data is "wrong" or not because if it is a mobile or fixedLine number using `null` should have the same effect.

Sorry for my misleading description about this issue.The number `53552200` is actually a valid phone number format in HK.

When I called `validate` method with this number.I got `false` return.And I tried all three patterns in HK metadata.The general one is matched.

I think it's an issue about Google's libphonenumber though.

It will be nice if I can validate this number with general pattern successfully as a workaround :)

Feel free to close this issue for I have already fired an issue to libphonenumber team.

**Comment by codenoobforreal** [comment]
this number is spare.I will close this issue.

**Comment by cedvdb** [comment]
What do you mean by "this number is spare" ? Could you link to your issue ?

**Comment by codenoobforreal** [comment]
> What do you mean by "this number is spare" ? Is it a phone number not in use ? Could you link to your issue ?

This number is not in use. 
document below.
<img width="988" alt="DBAB00CB-36CE-42CC-B7F0-4C09B7415605" src="https://user-images.githubusercontent.com/18373253/147215402-e6546231-8829-4c9f-a7ee-6df503f70514.png">

issue link:https://issuetracker.google.com/issues/211830866
