### ISSUE TITLE
With the 5.0.0 version, it's impossible to validate phone numbers for an arbitrary country

### ISSUE THREAD

**Issue by Zverik** [cedvdb/phone_numbers_parser#24]
Since 5.0.0, instead of specifying a country ISO code as string, this library requires using the generated enum. This is fine when a country is known at compilation time, but for multi-national apps it breaks the workflow. All I know is a string. Even if it were a enum, it would be a different enum, coming from a different library.

Is there a way to use string ISO codes with this library?

**Comment by cedvdb** [comment]
Dart enums are possible to be created with a String, but I'll add a constructor to faciliate the process.

in the mean time you can use `Enum.values.byName(your_string)` so in this case `IsoCode.values.byName('YOUR String')`

**Comment by cedvdb** [comment]
I've updated the readme with an example. Feel free to reopen if that's not your issue
