### ISSUE TITLE
Can you add format to international format

### ISSUE THREAD

**Issue by Ilkhom-S** [cedvdb/phone_numbers_parser#28]
Hello, 
Can you add formatting option to international format. 

I'm writing TextInputFormatter class for this librarry. Need to output national and international format 

Thanks in advance

**Comment by cedvdb** [comment]
The project is open for pull request yes. 

Do you have a rough overview on how you are going to tackle this issue ?

Thanks in advance

**Comment by cedvdb** [comment]
Here is the relevant file: https://github.com/cedvdb/phone_numbers_parser/blob/dev/lib/src/formatters/phone_number_formatter.dart

and you might need to update the metadata library. Closing as this is not an issue and I've no plans to put free work in this.
