### ISSUE TITLE
migrate to fromRaw

### ISSUE THREAD

**Issue by cedvdb** [cedvdb/phone_numbers_parser#29]
The addition of the two parameters to `fromRaw` seems to be a more logical API. I've deprecated the other constructors as of now, before removing those in the future.

steps required to remove others:

  - migrate tests
  - remove unnecessary methods and factories on `phoneNumber` and `parser`

**Comment by cedvdb** [comment]
@mrclauss Could I have your opinion on this as it's fresh in your mind ?

**Comment by mrclauss** [comment]
I think that would work, fromNational should behave as if you use fromRaw with a callerCountry. fromIso probably too. Only fromCountry is a bit different as it searches for a best match to find the most suitable isoCode matching the national number given a countryCode. That one needs to be checked in more detail in my opinion.

**Comment by cedvdb** [comment]
Yes I've noticed while implementing it. Thanks.
