### ISSUE TITLE
Is it possible to get the mask that is used to format the number?

### ISSUE THREAD

**Issue by jodinathan** [cedvdb/phone_numbers_parser#33]
Basically I need to use the mask formatter to make the input have the mask as placeholder like `(__) _____ ____`

**Comment by cedvdb** [comment]
Hooo, I'm not exactly sure how that will be accomplished. Please check phone_numbers_metadata library to see the formats of the phone number "Format". If I recall correctly, patterns are used

**Comment by cedvdb** [comment]
Maybe it's doable https://github.com/cedvdb/dart_phone_metadata/blob/main/lib/src/generated/metadata_formats_by_iso_code.dart

**Comment by jodinathan** [comment]
Maybe I could exec the formatter on an example of that specific country and phone type then replace the digits to `_` mask?  

for BR country the example is like `(15) 98765 9140`, so I would replace the digits and end up with `(__) _____ ____`

**Comment by cedvdb** [comment]
I guess but there are different formats for one country

**Comment by cedvdb** [comment]
> so I guess the best option is to understand the formatter and generate a mask from that.
> it would be a hell of an addition to the lib

You could use the method previously talked about to generate the masks, there will simply be multiple masks possible for one country

**Comment by jodinathan** [comment]
I guess the countries that has more than one format the users are used to not have a mask, so I would only mask the inputs that has only one format for mobile phone numbers

**Comment by cedvdb** [comment]
It's kind of a cool feature though and I think the mask can be generated on the fly, so it could be a simple method.

However I think it would be far easier to use an already generated mask library. I don't think the metadata was thought with masks in mind

**Comment by jodinathan** [comment]
>  In my country for example the formatting is not the same for mobile and fixed line.

yeah, here in Brazil is the same, but it would still be a nice addition as we basically ask for mobile number in 99% of the signing up forms
