### ISSUE TITLE
Format vs intlFormat?

### ISSUE THREAD

**Issue by jaustin42** [cedvdb/phone_numbers_parser#42]
I noticed our US national format is coming out as XXX-XXX-XXXX instead of (XXX) XXX-XXXX as with the javascript google library .  It looks to be this code:

```
   var transformRule = formatingRule.format;
    // if there is an international format, we use it
    final intlFormat = formatingRule.intlFormat;
    if (intlFormat != null && intlFormat != 'NA') {
      transformRule = intlFormat;
    }
```

I'm not sure the intended usage here.   Maybe there should be a different formatter for national formats?  The international format also produces "+1 XXX-XXX-XXXX" for international in the javascript code.

**Comment by cedvdb** [comment]
Sorry for the late reply. Could you make a proposal ?

**Comment by jaustin42** [comment]
I'm just not sure why it overrides with intlFormat when format is the national format.  For example the US data.

```
    PhoneMetadataFormat(
      pattern: r"(\d{3})(\d{3})(\d{4})",
      nationalPrefixFormattingRule: null,
      leadingDigits: ["[2-9]"],
      format: r"($1) $2-$3",
      intlFormat: r"$1-$2-$3",
    )
```

The (###) ###-### is the preferred national format rather than  ###-###-###.

**Comment by cedvdb** [comment]
Tbh that's a mistake. 

A new api could look like

```
  enum Format { national, international }

  PhoneNumber.formt([ Format.national ])
```

**Comment by cedvdb** [comment]
@jaustin42 would you be interested in providing a PR for this ?

**Comment by cedvdb** [comment]
added 
![image](https://github.com/user-attachments/assets/d2deedf0-5d85-46c5-bae4-fed558383be1)
