### ISSUE TITLE
Problem in format Canada phone number

### ISSUE THREAD

**Issue by Abolfazlnezami2000** [cedvdb/phone_numbers_parser#45]
I tried to reformat the Canada Phone number but the package is not working.
![image](https://github.com/cedvdb/phone_numbers_parser/assets/56001422/c8817289-ec3a-497d-b530-489f97047386)
![image](https://github.com/cedvdb/phone_numbers_parser/assets/56001422/6b9265b6-a06d-49c3-95fa-ffa0b2f96c6f)
but the main package worked :
https://libphonenumber.appspot.com/phonenumberparser?number=8195555555&country=CA

**Comment by cedvdb** [comment]
Here is the source code if someone wants to look into this: https://github.com/cedvdb/phone_numbers_parser/blob/main/lib/src/formatting/phone_number_formatter.dart

**Comment by cedvdb** [comment]
> Hi Any chance to support all formats from like `phoneNumber.e164` and so on?

I will review a pull request that adds that functionality

**Comment by cedvdb** [comment]
should be added in last update
