### ISSUE TITLE
Wrong result obtained from local number

### ISSUE THREAD

**Issue by aazhevsky** [cedvdb/phone_numbers_parser#46]
Hello,

I found an embarrassing error while resolving local numbers with a preferred country code from the device locale.

Parsing the local phone number ~`(555) 522-8243`~  `(707) 555-1854` (local US number, successfully validated with different tools) and callerCountry set to `IsoCode.US` returns a result that doesn't seem to be valid:

~`PhoneNumber(isoCode: IsoCode.BR, countryCode: 55, nsn: 5555228243)`~ `PhoneNumber(isoCode: IsoCode.RU, countryCode: 7, nsn: 7075551854)`

I assume, that 'callerCountry' should be prioritized over the country code retrieved from the number if no exit code was supplied.

**Comment by cedvdb** [comment]
Note that this library is a dart only library. It would be nice to edit your comment to not pollute the actual issue with IOS, device references for future readers

**Comment by aazhevsky** [comment]
Thanks for your reply. 

>It would be nice to edit your comment to not pollute the actual issue with IOS and device references for future readers.

Since this library doesn't use libphonenumber or PhoneNumberKit as dependencies, I guess the issue should persist on other platforms too, shouldn't it?

My bad, the number `(555) 522-8243` wasn't a good example. It's invalid, although libphonenumber can convert it to the international format. 

Another good (and verified) example is `(707) 555-1854` that results in `PhoneNumber(isoCode: IsoCode.RU, countryCode: 7, nsn: 7075551854)`

On the other hand, the `phone_number` library for Flutter returns `PhoneNumber { countryCode: 1, regionCode: US, e164: +17075551854, national: (707) 555-1854, type: PhoneNumberType.FIXED_LINE_OR_MOBILE, international: +1 707-555-1854, nationalNumber: 7075551854 }`, which is the valid result.

> Could you also provide the code with the expected result?

Sorry, I didn't have enough time to debug the library. Does the sample with `phone_number` count for this?

**Comment by cedvdb** [comment]
It's a small thing but this library has nothing to do with the platforms you are using, you'd have the same issue in all environment. So it's irrelevant to the issue.

 > Does the sample with phone_number count for this?

Yes. Thanks

**Comment by cedvdb** [comment]
@aazhevsky are you going to look into this ?

**Comment by aazhevsky** [comment]
@cedvdb, if you are waiting for suggestions from my side, I plan to start today. Or is there something else I expected to do?

**Comment by cedvdb** [comment]
@aazhevsky That's great. Don't hesitate to post here if you have questions.

**Comment by cedvdb** [comment]
should be fixed on dev currently.
