### ISSUE TITLE
[Feature request] support VOIP

### ISSUE THREAD

**Issue by CLazarini** [cedvdb/phone_numbers_parser#48]
Hello,

When using the .isValid() method on the following number: +33 9 67 49 76 70, it returns false.
Using the libphonenumber [validator](https://libphonenumber.appspot.com/phonenumberparser?number=+33967497670) it correctly identifies it as valid.

Reproduced on both 7.0.2 and 8.0.0.

`print(PhoneNumber.parse("+33 9 67 49 76 70").isValid());`

**Comment by cedvdb** [comment]
Currently only fixed line and mobile phone numbers are supported.  Feel free to implement that

**Comment by CLazarini** [comment]
Alright thanks for the infos, will do whenever I got some free time :)
