### ISSUE TITLE
Validating Indian mobile number with ISO Code: US(countryCode: 1) and return true

### ISSUE THREAD

**Issue by gh-vipinchouhan** [cedvdb/phone_numbers_parser#63]
PhoneNumber number = PhoneNumber.parse(phone,callerCountry: IsoCode.fromJson(isoCode));
    print("Phone is ${phone} ISO is ${isoCode} caller country ${IsoCode.fromJson(isoCode)} destination country ${IsoCode.fromJson(isoCode)}, formatted number with caller country ${PhoneNumber.parse(phone,destinationCountry: IsoCode.fromJson(isoCode))} isvalid ${number.isValid(type: PhoneNumberType.mobile)}");

    if(number.isValid(type: PhoneNumberType.mobile)){
      return true;
    }

**Result**
Phone is **8386943341** ISO is **US** caller country IsoCode.US destination country IsoCode.US, formatted number with caller country PhoneNumber(isoCode: IsoCode.US, countryCode: 1, nsn: **8386943341**) isvalid **true**

Actually when i try for validated some indian mobile number then above code giving valid number with ISO code US and country code 1 but if we use indian number with +1 country code then it should return false

**Comment by BeeCM** [comment]
The number which we giving start with the country code as per US 838 you mentioned above Eastern Upstate New York so the number will get accepted .Am stuck with the same issue that the Indian number given is returning true for country US.

**Comment by cedvdb** [comment]
You did not provide a reproducible example.

**Comment by cedvdb** [comment]
I'm closing this as innactionable. Please open a proper issue.

**Comment by BeeCM** [comment]
if you select the country code US and number from india the OTP
getting send there is no validation there
