### ISSUE TITLE
Question: Format with parentheses

### ISSUE THREAD

**Issue by eliasreis54** [cedvdb/phone_numbers_parser#71]
Hi!

I have a quick question. I reviewed the documentation, but it did not specify how to format a phone number with parentheses. For example, I want to format +15575519473 to appear as (557) 551-9473.

Is there a way to apply this formatting?

Thank you in advance!

**Comment by cedvdb** [comment]
Do you know what kind of formatting that is ? Currently the format method uses the international version but there is an issue that hints that adding additional formats would be helpful. Unfortunately I don't have the time to add that currently

**Comment by eliasreis54** [comment]
According to the [JS demo ](https://github.com/google/libphonenumber?tab=readme-ov-file#javascript) from [libphonenumber](https://github.com/google/libphonenumber) library, the format is supposed to be the National format

![Screenshot 2024-07-31 at 23 36 23](https://github.com/user-attachments/assets/e534aab4-75d6-47b7-9664-929ae19c2c5c)

If you think it's worth adding this new format style, I'm open to try working on that.

**Comment by cedvdb** [comment]
> If you think it's worth adding this new format style, I'm open to try working on that.

Great. how do you envision this ? I've in mind:

```dart
  enum Format { national, international }

  PhoneNumber.format([ Format format = Format.national ]) {
     // ...
  }

```

**Comment by eliasreis54** [comment]
I agree with you @cedvdb, let me try to put up a proposal, so we can discuss about that.

**Comment by cedvdb** [comment]
Great. You can see that here the international rule is used (instead of the national) https://github.com/cedvdb/phone_numbers_parser/blob/main/lib/src/formatting/phone_number_formatter.dart#L33

**Comment by cedvdb** [comment]
![image](https://github.com/user-attachments/assets/44c594b2-0100-4a0c-b372-76674a66645a)
