### ISSUE TITLE
Support New Benin Phone Number Format (Forced Effective November 30, 2024)

### ISSUE THREAD

**Issue by ManindraDeMel** [cedvdb/phone_numbers_parser#77]
# Support New Benin Phone Number Format (Effective November 30, 2024)

## Description

Benin updated its phone number format on November 30, 2024, to accommodate the increasing number of users. The change includes the addition of the "01" prefix to all existing numbers, extending the total length to 10 digits.

### New Format Details:
- **Country Code:** +229
- **Prefix:** 01 (new)
- **Example Conversion:**
  - Old Format: +229 97 00 00 00
  - New Format: +229 01 97 00 00 00

### Key Requirements:
1. Update the library to validate the new 10-digit phone numbers in Benin.
2. Ensure backward compatibility with the 8-digit numbers by recognizing and converting them into the new format.
3. Add test cases to verify both existing and new formats.

### References:
- [Pawapay Blog - Benin Phone Number Format Change](https://www.pawapay.io/blog/benins-new-phone-number-format)
- [Wikipedia - Telephone Numbers in Benin](https://en.wikipedia.org/wiki/Telephone_numbers_in_Benin)

**Comment by ManindraDeMel** [comment]
It appears that the changes to support Benin's updated phone number format (effective October 31, 2024) have already been implemented in the metadata. Specifically:

The "01" prefix for 10-digit numbers is present in the patterns.
Legacy 8-digit numbers are still recognized.
Both PhoneMetadataFormatListDefinition and PhoneMetadataPatterns reflect these updates.
However, after testing, the following issues were observed:

Parsing: The library fails to correctly identify or parse some valid 10-digit numbers with the "01" prefix.
Formatting: Numbers that should follow the new 10-digit format are not being formatted as expected (e.g., +229 01 XX XX XX XX).
Validation: Certain valid numbers are incorrectly flagged as invalid.

**Comment by ManindraDeMel** [comment]
ah, i see in commit 9bb32eb that the changes were made yesterday. When will this be released?

**Comment by cedvdb** [comment]
This repo would really benefit from an auto publish action, but I've no time to add that yet.

Will release now.

**Comment by ManindraDeMel** [comment]
> This repo would really benefit from an auto publish action, but I've no time to add that yet.
> 
> Will release now.

Happy to do the work for it if you wanted to assign me the ticket?

**Comment by ManindraDeMel** [comment]
> There is this issue #73 . Do you want / need write access ?

yeah for the ENV

**Comment by cedvdb** [comment]
I do not think you need write access for this.

I added the following configuration to the package on pub.dev

![image](https://github.com/user-attachments/assets/13eea74c-2fa0-4e3e-864c-c9028aa6bd39)

**Comment by ManindraDeMel** [comment]
Cool thanks ill get on it soon
